services:
    _defaults:
        autoconfigure: true
        autowire: false

    Terminal42\ImageDeleteBundle\Controller\ImageDeleteController:
        arguments:
            - '@contao.framework'
            - '@security.helper'
            - '@twig'
            - '@router'
            - '@filesystem'
            - '@contao.csrf.token_manager'
            - '%kernel.project_dir%'
            - '%contao.image.target_dir%'
        public: true

    Terminal42\ImageDeleteBundle\EventListener\FileDeleteOperationListener:
        arguments:
            - '@security.helper'
            - '@router'
            - '%kernel.project_dir%'
