services:
    _defaults:
        autoconfigure: true
        autowire: false

    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - [ setContainer, [ '@Psr\Container\ContainerInterface' ] ]

    Terminal42\ImageDeleteBundle\Controller\ImageDeleteController:
        arguments:
            - '@contao.framework'
            - '@security.authorization_checker'
            - '@router'
            - '@filesystem'
            - '@contao.csrf.token_manager'
            - '%kernel.project_dir%'
            - '%contao.image.target_dir%'

    Terminal42\ImageDeleteBundle\EventListener\FileDeleteOperationListener:
        arguments:
            - '@security.authorization_checker'
            - '@router'
            - '%kernel.project_dir%'
